# This is a basic workflow to help you get started with Actions

name: Build and deploy ASP.Net Core app to an Azure Web App

# Controls when the workflow will run
on: [push]

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
  deploy:
    runs-on: ubuntu-latest
