# File: .github/workflows/OIDC_workflow.yml

name: Run Azure Login with OIDC
on: [push]

env:
      WEBAPP: dxcgithub
      GROUP: Test-RG
      ACCOUNT: dxcgitstacc01
      CONTAINER: github-webapp
      EXPIRY_TIME: 10 minutes

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Set SAS token expiration
        run: echo "expiry=`date -u -d "$EXPIRY_TIME" '+%Y-%m-%dT%H:%MZ'`" >> $GITHUB_ENV
        
      - name: 'Run az commands'
        uses: azure/CLI@v1
        with:
            inlineScript: |
                  #az storage container create -n $CONTAINER --account-name $ACCOUNT --auth-mode login
                  #az storage blob upload      -f eShopOnWeb-main.zip    --account-name $ACCOUNT -c $CONTAINER -n $ACCOUNT --auth-mode login
                  ZIP_URL=$(az storage blob generate-sas --full-uri --permissions r --expiry ${{ env.expiry }} --account-name $ACCOUNT -c $CONTAINER -n $ACCOUNT | xargs)
                  echo $ZIP_URL
                  az webapp deploy --name $WEBAPP --resource-group $GROUP --type zip --src-url  $ZIP_URL --async false
